### ISSUE TITLE
Duplicate Paramater

### ISSUE THREAD

**Issue by pkpfr** [intercom/Intercom-OpenAPI#84]
`/tickets/{ticket_id}/reply` in v2.9 (possibly others) has a duplicate paramater:

```
"/tickets/{ticket_id}/reply":
    parameters:
    - name: ticket_id
      in: path
      description: ticket_id
      required: true
      schema:
        type: string
    post:
      summary: Create a ticket reply
      parameters:
      - name: Intercom-Version
        in: header
        schema:
          "$ref": "#/components/schemas/intercom_version"
      - name: ticket_id
        in: path
        required: true
        description: The unique identifier for the ticket which is given by Intercom
        schema:
          type: string
```

The first parameters block is redundant and caused generation of code for Go to fail.

`error generating code: error creating operation definitions: path '/tickets/{ticket_id}/reply' has 1 positional parameters, but spec has 2 declared`
